# name: Shelter Data Extraction Script
# 
# on:
#   workflow_dispatch:
#   push:
#     branches:
#       - main
#   schedule:
#     - cron: '*/10 * * * *'
# 
# jobs:
#   build-deploy:
#     runs-on: ubuntu-latest
# 
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v4
# 
#       - name: Install R
#         uses: r-lib/actions/setup-r@v2
#         with:
#           r-version: '4.4.0'
# 
#       - name: Install R Dependencies
#         uses: r-lib/actions/setup-renv@v2
#         with:
#           cache-version: 1
# 
#       - name: Run Data Extraction Script
#         run: Rscript dev/R/extract_shelter_data.R
# 
#       - name: Commit and push changes
#         if: success()
#         run: |
#           git config --global user.name "${{ secrets.USER_NAME }}"
#           git config --global user.email "${{ secrets.USER_EMAIL }}"
#           git add data .
#           git commit -m "Automated data extraction update"
#           git push
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
